### ISSUE TITLE
Clarify package lifecycle threshold for inclusion in r-universe

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/universe#8]
Currently, our r-universe contains a mix of packages in various development stages, which may create confusion. 

Since one major goal of r-universe is to allow automatic build of binaries to streamline package installation, it might make sense to only include packages ready for public use, as possibly indicated by the presence of a first GitHub release.

**Comment by pratikunterwegs** [comment]
I didn't comment on this issue initially as I have just noticed it and the resulting change, but I would prefer this change to be reversed.

Firstly, including packages in different development stages is unlikely to be an issue simply because there are not many users at the moment. I would expect that users who are seeking out an R-universe build are aware of what they are doing. @jamesmbaazam and I also recently encountered a case where somebody wanted to install {epidemics}, but had trouble compiling from source - providing binaries would help such cases.

Second, the previous configuration allowed for an easy way to view all Epiverse packages together, via https://epiverse-trace.r-universe.dev/packages. The current view is of only a few packages, which does not correctly represent the state of Epiverse development to prospective adopters.

Thirdly, having a Github release is not a great condition for inclusion. Our way of working is to make a Github release only along with a CRAN submission, so packages that are already MVPs and which I think should be included here, such as {epiparameter} or {cfr}, are not. I'm not yet convinced of the need for frequent Github releases.

Finally, when changing policies for infrastructure repos that most developers don't engage with frequently (no RSEs are watchers), it might be good to cross-post the proposed change in Slack to get more feedback.
